# Generated by Django 6.0.5 on 2026-05-07 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaSuplemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('recomendacao', models.TextField(blank=True)),
            ],
        ),
    ]
